/**
 * @layer    core
 * @module   events
 * @fires    none
 * @listens  none
 * @depends  none
 */

const events = {
    // Driver events
    CODE_SCANNED: 'CODE_SCANNED',
    CARD_SWIPED: 'CARD_SWIPED',
    EID_DETECTED: 'EID_DETECTED',
    FINGER_TOUCHED: 'FINGER_TOUCHED',
    GPIO_KEY_PRESSED: 'GPIO_KEY_PRESSED',
    INPUT_TRIGGERED: 'INPUT_TRIGGERED',
    NETWORK_CHANGED: 'NETWORK_CHANGED',
    MQTT_CHANGED: 'MQTT_CHANGED',
    FACE_DETECTED: 'FACE_DETECTED',
    FACE_RECOGNIZED: 'FACE_RECOGNIZED',
    NIR_PERSON_SAMPLED: 'NIR_PERSON_SAMPLED',
    INTERCOM_SERVICE_STATUS_CHANGED: 'INTERCOM_SERVICE_STATUS_CHANGED',
    INTERCOM_INCOMING: 'INTERCOM_INCOMING',
    INTERCOM_PRIMARY_INCOMING: 'INTERCOM_PRIMARY_INCOMING',
    INTERCOM_CALL_FAILED: 'INTERCOM_CALL_FAILED',
    INTERCOM_CALL_STARTED: 'INTERCOM_CALL_STARTED',
    INTERCOM_CALL_LINKED: 'INTERCOM_CALL_LINKED',
    INTERCOM_CALL_DISCONNECTED: 'INTERCOM_CALL_DISCONNECTED',
    INTERCOM_CALL_ENDED: 'INTERCOM_CALL_ENDED',
    INTERCOM_SESSION_STATE_CHANGED: 'INTERCOM_SESSION_STATE_CHANGED',
    INTERCOM_DATA_OPENED: 'INTERCOM_DATA_OPENED',
    INTERCOM_DATA_RECEIVED: 'INTERCOM_DATA_RECEIVED',

};

export default events;
